# File: C:/Users/Jamie/workspace/epos_mcp/epos_genesis.py
# Constitutional Authority: EPOS Constitution v3.1
# Governed: True
"""
EPOS Genesis - Bootstrap Script
Scaffolds all required directories and initializes the EPOS environment
"""

from pathlib import Path
import json
import logging
from datetime import datetime
from typing import Dict, List

class EPOSGenesis:
    def __init__(self, epos_root: Path):
        self.epos_root = Path(epos_root)
        
        # Setup logging
        log_file = self.epos_root / f"genesis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(log_file),
                logging.StreamHandler()
            ]
        )
        self.logger = logging.getLogger(__name__)
        
        # Directory structure to create
        self.required_dirs = [
            "context_vault",
            "context_vault/business_os",
            "context_vault/business_os/finance",
            "context_vault/business_os/operations",
            "context_vault/business_os/reports",
            "context_vault/life_os",
            "context_vault/life_os/energy",
            "context_vault/life_os/relationships",
            "context_vault/life_os/growth",
            "context_vault/life_os/purpose",
            "context_vault/missions",
            "context_vault/meta",
            "context_vault/meta/semantic",
            "logs",
            "inbox",
            "outbox",
            "containers",
            "containers/event-bus",
            "containers/governance",
            "containers/learning",
            "containers/context",
            "containers/jarvis",
            "containers/command-center",
            "engine",
            "ops"
        ]
        
        # Required files with templates
        self.required_files = {
            ".env": self._generate_env_template(),
            "context_vault/missions/EPISODES.jsonl": "",
            "context_vault/meta/semantic/az_preferences.jsonl": "",
            "ops/bi_decision_log.json": json.dumps([], indent=2)
        }
    
    def _generate_env_template(self) -> str:
        """Generate .env template (EPOS_ROOT/AGENT_ZERO_ROOT resolved at runtime)."""
        epos_root = os.getenv("EPOS_ROOT") or str(Path(__file__).resolve().parent)
        workspace = str(Path(epos_root).parent)
        agent_zero = os.getenv("AGENT_ZERO_ROOT") or str(Path(workspace) / "agent-zero")
        return f"""# EPOS Environment Configuration
# Generated by epos_genesis.py

EPOS_ROOT={epos_root}
AGENT_ZERO_ROOT={agent_zero}

# Service URLs
EVENT_BUS_URL=http://localhost:8100
GOVERNANCE_URL=http://localhost:8101
LEARNING_URL=http://localhost:8102
CONTEXT_URL=http://localhost:8103
JARVIS_URL=http://localhost:8104

# Python environment
PYTHONPATH=${EPOS_ROOT}

# Docker settings
COMPOSE_FILE=docker-compose-constitutional-3.yml
"""
    
    def create_directories(self):
        """Create all required directories"""
        self.logger.info("📁 Creating directory structure...")
        
        created = []
        skipped = []
        
        for dir_path in self.required_dirs:
            full_path = self.epos_root / dir_path
            
            if full_path.exists():
                skipped.append(str(dir_path))
            else:
                full_path.mkdir(parents=True, exist_ok=True)
                created.append(str(dir_path))
                self.logger.info(f"  ✅ Created: {dir_path}")
        
        self.logger.info(f"\n📊 Summary:")
        self.logger.info(f"  Created: {len(created)} directories")
        self.logger.info(f"  Skipped (already exist): {len(skipped)} directories")
        
        return created, skipped
    
    def create_files(self):
        """Create required files with templates"""
        self.logger.info("\n📄 Creating required files...")
        
        created = []
        skipped = []
        
        for file_path, content in self.required_files.items():
            full_path = self.epos_root / file_path
            
            if full_path.exists():
                skipped.append(str(file_path))
            else:
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.write_text(content, encoding='utf-8')
                created.append(str(file_path))
                self.logger.info(f"  ✅ Created: {file_path}")
        
        self.logger.info(f"\n📊 Summary:")
        self.logger.info(f"  Created: {len(created)} files")
        self.logger.info(f"  Skipped (already exist): {len(skipped)} files")
        
        return created, skipped
    
    def validate_structure(self) -> Dict:
        """Validate that all required directories and files exist"""
        self.logger.info("\n🔍 Validating EPOS structure...")
        
        missing_dirs = []
        missing_files = []
        
        for dir_path in self.required_dirs:
            full_path = self.epos_root / dir_path
            if not full_path.exists():
                missing_dirs.append(str(dir_path))
        
        for file_path in self.required_files.keys():
            full_path = self.epos_root / file_path
            if not full_path.exists():
                missing_files.append(str(file_path))
        
        valid = len(missing_dirs) == 0 and len(missing_files) == 0
        
        if valid:
            self.logger.info("✅ EPOS structure is valid")
        else:
            self.logger.warning("⚠️  EPOS structure has missing components:")
            for d in missing_dirs:
                self.logger.warning(f"  Missing dir: {d}")
            for f in missing_files:
                self.logger.warning(f"  Missing file: {f}")
        
        return {
            "valid": valid,
            "missing_dirs": missing_dirs,
            "missing_files": missing_files
        }
    
    def bootstrap(self):
        """Run complete bootstrap sequence"""
        self.logger.info("=" * 60)
        self.logger.info("🚀 EPOS Genesis - Bootstrap Starting")
        self.logger.info("=" * 60)
        self.logger.info(f"Root: {self.epos_root}\n")
        
        # Create directories
        created_dirs, skipped_dirs = self.create_directories()
        
        # Create files
        created_files, skipped_files = self.create_files()
        
        # Validate
        validation = self.validate_structure()
        
        # Final report
        self.logger.info("\n" + "=" * 60)
        self.logger.info("📋 BOOTSTRAP COMPLETE")
        self.logger.info("=" * 60)
        self.logger.info(f"Status: {'✅ SUCCESS' if validation['valid'] else '⚠️  PARTIAL'}")
        self.logger.info(f"Directories created: {len(created_dirs)}")
        self.logger.info(f"Files created: {len(created_files)}")
        
        if not validation['valid']:
            self.logger.warning("\n⚠️  Some components are missing. Run genesis again to fix.")
        
        return validation['valid']

def main():
    """CLI entry point"""
    import sys
    
    epos_root = Path.cwd()
    
    if len(sys.argv) > 1:
        epos_root = Path(sys.argv[1])
    
    genesis = EPOSGenesis(epos_root)
    success = genesis.bootstrap()
    
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
