# File: ${EPOS_ROOT}/agents/constitutional_arbiter.py

"""
Constitutional Arbiter (Agent Alpha) v1.0.0
==========================================

Constitutional Authority: EPOS_CONSTITUTION_v3.1.md Articles II, III, IV
Purpose: Enforce constitutional governance on every code change

This agent is the "immune system" of EPOS - no code enters /engine without
passing constitutional review. It generates educational receipts for failures
and tracks compliance metrics for the Flywheel Analyst.

Exit Codes:
    0 = All files compliant, promotion approved
    1 = Violations detected, files rejected with receipts
    2 = Critical constitutional violation requiring immediate intervention
"""

import sys
import os
import json
import ast
import re
import shutil
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, field, asdict
from enum import Enum

# Ensure Python 3.11+
if sys.version_info[:2] < (3, 11):
    print("❌ CRITICAL: Python 3.11+ required (Article II Rule 3)")
    sys.exit(2)


class ViolationSeverity(Enum):
    """Violation severity levels."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class Violation:
    """Represents a constitutional violation."""
    code: str
    severity: ViolationSeverity
    file_path: str
    line_number: Optional[int]
    message: str
    constitutional_reference: str
    fix_suggestion: str
    
    def to_dict(self) -> Dict:
        return {
            "code": self.code,
            "severity": self.severity.value,
            "file_path": self.file_path,
            "line_number": self.line_number,
            "message": self.message,
            "constitutional_reference": self.constitutional_reference,
            "fix_suggestion": self.fix_suggestion
        }


@dataclass
class AuditResult:
    """Result of auditing a single file."""
    file_path: str
    is_compliant: bool
    violations: List[Violation] = field(default_factory=list)
    checks_passed: List[str] = field(default_factory=list)
    audit_timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict:
        return {
            "file_path": self.file_path,
            "is_compliant": self.is_compliant,
            "violations": [v.to_dict() for v in self.violations],
            "checks_passed": self.checks_passed,
            "audit_timestamp": self.audit_timestamp
        }


@dataclass
class EducationalReceipt:
    """Educational receipt for rejected files."""
    file_path: str
    rejection_timestamp: str
    violations: List[Violation]
    total_violations: int
    constitutional_references: List[str]
    learning_resources: List[str]
    resubmission_checklist: List[str]
    
    def to_markdown(self) -> str:
        """Generate markdown receipt."""
        lines = [
            f"# Educational Rejection Receipt",
            f"",
            f"**File**: `{self.file_path}`",
            f"**Rejected**: {self.rejection_timestamp}",
            f"**Total Violations**: {self.total_violations}",
            f"",
            f"---",
            f"",
            f"## Violations Detected",
            f""
        ]
        
        for i, v in enumerate(self.violations, 1):
            lines.extend([
                f"### {i}. {v.code}: {v.message}",
                f"",
                f"- **Severity**: {v.severity.value.upper()}",
                f"- **Line**: {v.line_number or 'N/A'}",
                f"- **Constitutional Reference**: {v.constitutional_reference}",
                f"",
                f"**How to Fix**:",
                f"```",
                f"{v.fix_suggestion}",
                f"```",
                f""
            ])
        
        lines.extend([
            f"---",
            f"",
            f"## Constitutional References",
            f""
        ])
        for ref in self.constitutional_references:
            lines.append(f"- {ref}")
        
        lines.extend([
            f"",
            f"## Before Resubmitting",
            f""
        ])
        for item in self.resubmission_checklist:
            lines.append(f"- [ ] {item}")
        
        lines.extend([
            f"",
            f"## Learning Resources",
            f""
        ])
        for resource in self.learning_resources:
            lines.append(f"- {resource}")
        
        lines.extend([
            f"",
            f"---",
            f"",
            f"*Generated by Constitutional Arbiter (Agent Alpha)*",
            f"*Constitutional Authority: EPOS_CONSTITUTION_v3.1.md*"
        ])
        
        return "\n".join(lines)


class ConstitutionalArbiter:
    """
    Constitutional Arbiter - Agent Alpha
    
    Enforces EPOS Constitution on all code submissions.
    """
    
    # Violation code definitions
    VIOLATION_CODES = {
        "ERR-PATH-001": {
            "message": "Mixed path separators detected",
            "reference": "Article II Rule 1",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-PATH-002": {
            "message": "Relative path without explicit base",
            "reference": "Article II Rule 1",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-HEADER-001": {
            "message": "Missing constitutional file header",
            "reference": "Article II Rule 5",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-HEADER-002": {
            "message": "Header path mismatch with actual location",
            "reference": "Article II Rule 5",
            "severity": ViolationSeverity.WARNING
        },
        "ERR-CONFIG-001": {
            "message": "Entrypoint missing load_dotenv()",
            "reference": "Article II Rule 6",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-TRUTH-001": {
            "message": "Status returned without proof of execution",
            "reference": "Article II Rule 4",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-CONTEXT-001": {
            "message": "Inline data exceeds 8K token limit",
            "reference": "Article VII Section 1.1",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-CONTEXT-002": {
            "message": "Invalid context vault path reference",
            "reference": "Article VII Section 1.3",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-CONTEXT-003": {
            "message": "Mission references vault but file not found",
            "reference": "Article VII Section 4",
            "severity": ViolationSeverity.ERROR
        },
        "ERR-SYNTAX-001": {
            "message": "Python syntax error detected",
            "reference": "Article III (Quality Gates)",
            "severity": ViolationSeverity.CRITICAL
        },
        "ERR-DESTRUCT-001": {
            "message": "Destructive operation without confirmation",
            "reference": "Article II Rule 5",
            "severity": ViolationSeverity.CRITICAL
        }
    }
    
    # Required header pattern
    HEADER_PATTERN = re.compile(r'^# File: ([A-Z]:\\[^\n]+)$', re.MULTILINE)
    
    # Path mixing patterns
    UNIX_PATH_PATTERN = re.compile(r'/c/Users/|/home/|~/workspace')
    WINDOWS_PATH_PATTERN = re.compile(r'[A-Z]:\\')
    
    # Destructive command patterns
    DESTRUCTIVE_PATTERNS = [
        re.compile(r'\brm\s+-rf\b'),
        re.compile(r'\bdel\s+/[sS]\b'),
        re.compile(r'\bformat\b'),
        re.compile(r'\bshutdown\b'),
        re.compile(r'\.unlink\s*\(\s*\)'),  # Path.unlink() without checks
    ]
    
    def __init__(self, epos_root: Optional[Path] = None, verbose: bool = False):
        """Initialize the Constitutional Arbiter."""
        self.epos_root = epos_root or Path(os.getenv("EPOS_ROOT", "C:/Users/Jamie/workspace/epos_mcp"))
        self.verbose = verbose
        self.audit_log: List[AuditResult] = []
        
        # Load environment
        self._load_environment()
    
    def _load_environment(self):
        """Load .env file."""
        try:
            from dotenv import load_dotenv
            env_path = self.epos_root / ".env"
            if env_path.exists():
                load_dotenv(env_path)
        except ImportError:
            pass
    
    def _log(self, message: str):
        """Print message if verbose."""
        if self.verbose:
            print(f"[Arbiter] {message}")
    
    # =========================================================================
    # CHECK: File Header (Article II Rule 5)
    # =========================================================================
    
    def check_header(self, file_path: Path, content: str) -> List[Violation]:
        """Check for constitutional file header."""
        violations = []
        
        # Check header presence
        match = self.HEADER_PATTERN.search(content[:500])  # Check first 500 chars
        
        if not match:
            violations.append(Violation(
                code="ERR-HEADER-001",
                severity=ViolationSeverity.ERROR,
                file_path=str(file_path),
                line_number=1,
                message="Missing constitutional file header",
                constitutional_reference="Article II Rule 5",
                fix_suggestion=f"Add this header as the first line:\n# File: {(self.epos_root / file_path.name).as_posix()}"
            ))
        else:
            # Check header path matches expected location
            header_path = match.group(1)
            expected_path = str(self.epos_root / file_path.name).replace("/", chr(92))
            
            if header_path != expected_path:
                violations.append(Violation(
                    code="ERR-HEADER-002",
                    severity=ViolationSeverity.WARNING,
                    file_path=str(file_path),
                    line_number=1,
                    message=f"Header path mismatch: {header_path} vs expected {expected_path}",
                    constitutional_reference="Article II Rule 5",
                    fix_suggestion=f"Update header to:\n# File: {expected_path}"
                ))
        
        return violations
    
    # =========================================================================
    # CHECK: Path Discipline (Article II Rule 1)
    # =========================================================================
    
    def check_path_discipline(self, file_path: Path, content: str) -> List[Violation]:
        """Check for path mixing violations."""
        violations = []
        lines = content.split('\n')
        
        for i, line in enumerate(lines, 1):
            # Skip comments
            if line.strip().startswith('#'):
                continue
            
            has_unix = self.UNIX_PATH_PATTERN.search(line)
            has_windows = self.WINDOWS_PATH_PATTERN.search(line)
            
            # Mixed paths in same line
            if has_unix and has_windows:
                violations.append(Violation(
                    code="ERR-PATH-001",
                    severity=ViolationSeverity.ERROR,
                    file_path=str(file_path),
                    line_number=i,
                    message=f"Mixed path separators on line {i}",
                    constitutional_reference="Article II Rule 1",
                    fix_suggestion="Use Windows-style paths consistently. Convert Unix paths to Windows paths."
                ))
            
            # Unix-style path in code (not comment)
            elif has_unix and not line.strip().startswith(('#', '//', '"""', "'''")):
                violations.append(Violation(
                    code="ERR-PATH-001",
                    severity=ViolationSeverity.ERROR,
                    file_path=str(file_path),
                    line_number=i,
                    message=f"Unix-style path detected on line {i}",
                    constitutional_reference="Article II Rule 1",
                    fix_suggestion="Replace Unix-style paths with Windows-style paths (pathlib preferred)."
                ))
        
        return violations
    
    # =========================================================================
    # CHECK: Configuration Loading (Article II Rule 6)
    # =========================================================================
    
    def check_config_loading(self, file_path: Path, content: str) -> List[Violation]:
        """Check for proper .env loading at entrypoints."""
        violations = []
        
        # Only check files that look like entrypoints
        entrypoint_indicators = ['if __name__', 'def main(', 'app = FastAPI', 'uvicorn.run']
        is_entrypoint = any(ind in content for ind in entrypoint_indicators)
        
        if not is_entrypoint:
            return violations
        
        # Check for load_dotenv
        has_load_dotenv = 'load_dotenv' in content
        has_getenv = 'os.getenv' in content or 'os.environ' in content
        
        if has_getenv and not has_load_dotenv:
            violations.append(Violation(
                code="ERR-CONFIG-001",
                severity=ViolationSeverity.ERROR,
                file_path=str(file_path),
                line_number=None,
                message="Entrypoint uses os.getenv but missing load_dotenv()",
                constitutional_reference="Article II Rule 6",
                fix_suggestion="""Add at the top of the file:
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parent / ".env")"""
            ))
        
        return violations
    
    # =========================================================================
    # CHECK: Context Vault Compliance (Article VII)
    # =========================================================================
    
    def check_context_compliance(self, file_path: Path, content: str) -> List[Violation]:
        """Check for inline data exceeding 8K token limit."""
        violations = []
        
        # Estimate tokens (1 token ≈ 4 characters)
        estimated_tokens = len(content) / 4
        
        # For JSON files, check for large inline data
        if file_path.suffix == '.json':
            try:
                data = json.loads(content)
                
                # Check for large string fields
                def check_large_strings(obj, path=""):
                    if isinstance(obj, str) and len(obj) > 8000:  # ~2K tokens
                        violations.append(Violation(
                            code="ERR-CONTEXT-001",
                            severity=ViolationSeverity.ERROR,
                            file_path=str(file_path),
                            line_number=None,
                            message=f"Large inline string at {path} (~{len(obj)//4} tokens)",
                            constitutional_reference="Article VII Section 1.1",
                            fix_suggestion=f"Move this data to context_vault/mission_data/ and reference via context_vault_path"
                        ))
                    elif isinstance(obj, dict):
                        for k, v in obj.items():
                            check_large_strings(v, f"{path}.{k}")
                    elif isinstance(obj, list):
                        for i, v in enumerate(obj):
                            check_large_strings(v, f"{path}[{i}]")
                
                check_large_strings(data)
                
                # Check for context_vault_path when file is large
                if estimated_tokens > 8192 and 'context_vault_path' not in data:
                    violations.append(Violation(
                        code="ERR-CONTEXT-001",
                        severity=ViolationSeverity.ERROR,
                        file_path=str(file_path),
                        line_number=None,
                        message=f"Mission spec exceeds 8K tokens ({int(estimated_tokens)}) without context_vault_path",
                        constitutional_reference="Article VII Section 1.3",
                        fix_suggestion="Add context_vault_path field pointing to vault file, or reduce inline data"
                    ))
                
            except json.JSONDecodeError:
                pass  # Not valid JSON, skip this check
        
        # For Python files, check for large string literals
        if file_path.suffix == '.py':
            # Find large string literals
            string_pattern = re.compile(r'"""[\s\S]{8000,}?"""|\'\'\'[\s\S]{8000,}?\'\'\'')
            for match in string_pattern.finditer(content):
                start_line = content[:match.start()].count('\n') + 1
                violations.append(Violation(
                    code="ERR-CONTEXT-001",
                    severity=ViolationSeverity.ERROR,
                    file_path=str(file_path),
                    line_number=start_line,
                    message=f"Large inline string literal (~{len(match.group())//4} tokens)",
                    constitutional_reference="Article VII Section 1.1",
                    fix_suggestion="Move large text to context_vault/ and load via ContextVault.load()"
                ))
        
        return violations
    
    # =========================================================================
    # CHECK: Syntax Validation (Article III)
    # =========================================================================
    
    def check_syntax(self, file_path: Path, content: str) -> List[Violation]:
        """Validate Python syntax via AST parsing."""
        violations = []
        
        if file_path.suffix != '.py':
            return violations
        
        try:
            ast.parse(content)
        except SyntaxError as e:
            violations.append(Violation(
                code="ERR-SYNTAX-001",
                severity=ViolationSeverity.CRITICAL,
                file_path=str(file_path),
                line_number=e.lineno,
                message=f"Syntax error: {e.msg}",
                constitutional_reference="Article III (Quality Gates)",
                fix_suggestion=f"Fix syntax error at line {e.lineno}: {e.msg}"
            ))
        
        return violations
    
    # =========================================================================
    # CHECK: Destructive Operations (Article II Rule 5)
    # =========================================================================
    
    def check_destructive_operations(self, file_path: Path, content: str) -> List[Violation]:
        """Check for destructive operations without safeguards."""
        violations = []
        lines = content.split('\n')
        
        for i, line in enumerate(lines, 1):
            for pattern in self.DESTRUCTIVE_PATTERNS:
                if pattern.search(line):
                    violations.append(Violation(
                        code="ERR-DESTRUCT-001",
                        severity=ViolationSeverity.CRITICAL,
                        file_path=str(file_path),
                        line_number=i,
                        message=f"Destructive operation detected on line {i}",
                        constitutional_reference="Article II Rule 5",
                        fix_suggestion="Wrap destructive operations with confirmation checks and backup logic"
                    ))
        
        return violations
    
    # =========================================================================
    # MAIN AUDIT FUNCTION
    # =========================================================================
    
    def audit_file(self, file_path: Path) -> AuditResult:
        """Run all constitutional checks on a file."""
        self._log(f"Auditing: {file_path}")
        
        violations = []
        checks_passed = []
        
        try:
            content = file_path.read_text(encoding='utf-8', errors='ignore')
        except Exception as e:
            return AuditResult(
                file_path=str(file_path),
                is_compliant=False,
                violations=[Violation(
                    code="ERR-READ-001",
                    severity=ViolationSeverity.CRITICAL,
                    file_path=str(file_path),
                    line_number=None,
                    message=f"Could not read file: {e}",
                    constitutional_reference="Article III",
                    fix_suggestion="Ensure file is readable and has valid encoding"
                )]
            )
        
        # Run all checks
        checks = [
            ("Header", self.check_header),
            ("Path Discipline", self.check_path_discipline),
            ("Config Loading", self.check_config_loading),
            ("Context Compliance", self.check_context_compliance),
            ("Syntax", self.check_syntax),
            ("Destructive Operations", self.check_destructive_operations),
        ]
        
        for check_name, check_func in checks:
            try:
                check_violations = check_func(file_path, content)
                if check_violations:
                    violations.extend(check_violations)
                else:
                    checks_passed.append(check_name)
            except Exception as e:
                self._log(f"  Warning: {check_name} check failed: {e}")
        
        is_compliant = len(violations) == 0
        
        result = AuditResult(
            file_path=str(file_path),
            is_compliant=is_compliant,
            violations=violations,
            checks_passed=checks_passed
        )
        
        self.audit_log.append(result)
        return result
    
    def audit_directory(self, directory: Path, extensions: List[str] = None) -> List[AuditResult]:
        """Audit all files in a directory."""
        extensions = extensions or ['.py', '.json']
        results = []
        
        for ext in extensions:
            for file_path in directory.glob(f'*{ext}'):
                if file_path.is_file():
                    result = self.audit_file(file_path)
                    results.append(result)
        
        return results
    
    # =========================================================================
    # FILE TRIAGE (Move to engine or rejected)
    # =========================================================================
    
    def triage_file(self, file_path: Path, dry_run: bool = False) -> Tuple[str, Optional[Path]]:
        """
        Triage a file: promote to /engine or reject with receipt.
        
        Returns:
            Tuple of (action, destination_path)
            action: "promoted", "rejected", or "skipped"
        """
        result = self.audit_file(file_path)
        
        if result.is_compliant:
            # Promote to engine
            engine_path = self.epos_root / "engine" / file_path.name
            
            if not dry_run:
                engine_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(file_path, engine_path)
                self._log(f"  ✅ Promoted: {file_path.name} → engine/")
            else:
                self._log(f"  ✅ Would promote: {file_path.name} → engine/")
            
            return "promoted", engine_path
        
        else:
            # Reject with educational receipt
            rejected_path = self.epos_root / "rejected" / file_path.name
            receipt_path = self.epos_root / "rejected" / "receipts" / f"{file_path.stem}_receipt.md"
            
            # Generate receipt
            receipt = EducationalReceipt(
                file_path=str(file_path),
                rejection_timestamp=datetime.now().isoformat(),
                violations=result.violations,
                total_violations=len(result.violations),
                constitutional_references=list(set(v.constitutional_reference for v in result.violations)),
                learning_resources=[
                    "EPOS_CONSTITUTION_v3.1.md - Full constitutional reference",
                    "PATH_CLARITY_RULES.md - Path discipline guidelines",
                    "FAILURE_SCENARIOS.md - Pre-mortem analysis examples"
                ],
                resubmission_checklist=[
                    f"Fix {v.code}: {v.message}" for v in result.violations
                ] + [
                    "Run: python governance_gate.py --check-file <your_file>",
                    "Verify all checks pass",
                    "Resubmit to inbox/"
                ]
            )
            
            if not dry_run:
                rejected_path.parent.mkdir(parents=True, exist_ok=True)
                receipt_path.parent.mkdir(parents=True, exist_ok=True)
                
                shutil.copy2(file_path, rejected_path)
                receipt_path.write_text(receipt.to_markdown())
                
                self._log(f"  🚫 Rejected: {file_path.name} ({len(result.violations)} violations)")
                self._log(f"     Receipt: {receipt_path}")
            else:
                self._log(f"  🚫 Would reject: {file_path.name} ({len(result.violations)} violations)")
            
            return "rejected", rejected_path
    
    def triage_inbox(self, dry_run: bool = False) -> Dict:
        """Triage all files in inbox/."""
        inbox = self.epos_root / "inbox"
        
        if not inbox.exists():
            return {"error": "inbox/ directory not found"}
        
        results = {
            "promoted": [],
            "rejected": [],
            "timestamp": datetime.now().isoformat()
        }
        
        for file_path in inbox.iterdir():
            if file_path.is_file() and file_path.suffix in ['.py', '.json']:
                action, dest = self.triage_file(file_path, dry_run=dry_run)
                results[action].append({
                    "file": file_path.name,
                    "destination": str(dest) if dest else None
                })
        
        # Log to BI
        if not dry_run:
            self._log_to_bi(results)
        
        return results
    
    def _log_to_bi(self, triage_results: Dict):
        """Log triage results to BI decision log."""
        bi_log_path = self.epos_root / "bi_decision_log.json"
        
        try:
            if bi_log_path.exists():
                bi_data = json.loads(bi_log_path.read_text())
            else:
                bi_data = {"decisions": []}
            
            bi_data["decisions"].append({
                "agent": "constitutional_arbiter",
                "action": "triage_inbox",
                "timestamp": triage_results["timestamp"],
                "promoted_count": len(triage_results["promoted"]),
                "rejected_count": len(triage_results["rejected"]),
                "files": {
                    "promoted": [f["file"] for f in triage_results["promoted"]],
                    "rejected": [f["file"] for f in triage_results["rejected"]]
                }
            })
            
            bi_log_path.write_text(json.dumps(bi_data, indent=2))
        except Exception as e:
            self._log(f"Warning: Could not log to BI: {e}")
    
    # =========================================================================
    # SPRINT BOUNDARY AUDIT
    # =========================================================================
    
    def sprint_audit(self) -> Dict:
        """Run full sprint boundary audit on engine/."""
        self._log("Running sprint boundary audit...")
        
        engine = self.epos_root / "engine"
        if not engine.exists():
            return {"error": "engine/ directory not found"}
        
        results = self.audit_directory(engine)
        
        total = len(results)
        compliant = sum(1 for r in results if r.is_compliant)
        
        governance_score = (compliant / total * 100) if total > 0 else 100
        
        # Aggregate violations by type
        violations_by_type = {}
        for result in results:
            for v in result.violations:
                violations_by_type[v.code] = violations_by_type.get(v.code, 0) + 1
        
        audit_report = {
            "timestamp": datetime.now().isoformat(),
            "governance_score": round(governance_score, 2),
            "total_files": total,
            "compliant_files": compliant,
            "non_compliant_files": total - compliant,
            "violations_by_type": violations_by_type,
            "files_with_violations": [
                r.to_dict() for r in results if not r.is_compliant
            ]
        }
        
        # Save report
        reports_dir = self.epos_root / "ops" / "logs" / "arbiter"
        reports_dir.mkdir(parents=True, exist_ok=True)
        
        report_path = reports_dir / f"sprint_audit_{datetime.now().strftime('%Y%m%d')}.json"
        report_path.write_text(json.dumps(audit_report, indent=2))
        
        # Log to BI
        bi_log_path = self.epos_root / "bi_decision_log.json"
        try:
            if bi_log_path.exists():
                bi_data = json.loads(bi_log_path.read_text())
            else:
                bi_data = {"decisions": []}
            
            bi_data["decisions"].append({
                "agent": "constitutional_arbiter",
                "action": "sprint_boundary_audit",
                "timestamp": audit_report["timestamp"],
                "governance_score": audit_report["governance_score"],
                "violations_summary": violations_by_type
            })
            
            bi_log_path.write_text(json.dumps(bi_data, indent=2))
        except Exception as e:
            self._log(f"Warning: Could not log to BI: {e}")
        
        return audit_report


def main():
    """CLI entrypoint for Constitutional Arbiter."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Constitutional Arbiter (Agent Alpha)")
    parser.add_argument("--check-file", type=str, help="Audit a specific file")
    parser.add_argument("--triage-inbox", action="store_true", help="Triage all files in inbox/")
    parser.add_argument("--sprint-audit", action="store_true", help="Run sprint boundary audit")
    parser.add_argument("--dry-run", action="store_true", help="Preview actions without moving files")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument("--json", "-j", action="store_true", help="JSON output")
    
    args = parser.parse_args()
    
    arbiter = ConstitutionalArbiter(verbose=args.verbose)
    
    if args.check_file:
        file_path = Path(args.check_file)
        if not file_path.exists():
            print(f"❌ File not found: {file_path}")
            sys.exit(1)
        
        result = arbiter.audit_file(file_path)
        
        if args.json:
            print(json.dumps(result.to_dict(), indent=2))
        else:
            if result.is_compliant:
                print(f"✅ COMPLIANT: {file_path}")
                print(f"   Checks passed: {', '.join(result.checks_passed)}")
            else:
                print(f"🚫 NON-COMPLIANT: {file_path}")
                print(f"   Violations: {len(result.violations)}")
                for v in result.violations:
                    print(f"   - {v.code}: {v.message}")
        
        sys.exit(0 if result.is_compliant else 1)
    
    elif args.triage_inbox:
        results = arbiter.triage_inbox(dry_run=args.dry_run)
        
        if args.json:
            print(json.dumps(results, indent=2))
        else:
            print(f"\n{'[DRY RUN] ' if args.dry_run else ''}Triage Results:")
            print(f"  Promoted: {len(results.get('promoted', []))}")
            print(f"  Rejected: {len(results.get('rejected', []))}")
        
        sys.exit(0)
    
    elif args.sprint_audit:
        report = arbiter.sprint_audit()
        
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"\n📊 Sprint Audit Report")
            print(f"   Governance Score: {report.get('governance_score', 0)}%")
            print(f"   Compliant: {report.get('compliant_files', 0)}/{report.get('total_files', 0)}")
            
            if report.get('violations_by_type'):
                print(f"\n   Violations by Type:")
                for code, count in report['violations_by_type'].items():
                    print(f"     {code}: {count}")
        
        sys.exit(0 if report.get('governance_score', 0) >= 95 else 1)
    
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
