# File: C:\Users\Jamie\workspace\epos_mcp\agents\flywheel_analyst.py

"""
Flywheel Analyst (Agent Omega) v1.0.0
=====================================

Constitutional Authority: EPOS_CONSTITUTION_v3.1.md Articles VIII, IX
Purpose: Transform BI logs into strategy; propose governance and product changes

This agent tracks the four EPOS flywheels:
1. Content Flywheel: Content → Engagement → Data → Better Content
2. Revenue Flywheel: Node Sales → Development → Better Nodes → More Sales
3. Data Moat Flywheel: More Data → Better Models → Better Output → More Data
4. Sovereign Scaling: Independence → Composability → Market Reach → More Independence

Exit Codes:
    0 = Analysis complete, all flywheels healthy
    1 = Warnings detected (some flywheels underperforming)
    2 = Critical issues (flywheels stalled, amendments needed)
"""

import sys
import os
import json
import re
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass, field, asdict
from collections import Counter
from enum import Enum

# Ensure Python 3.11+
if sys.version_info[:2] < (3, 11):
    print("❌ CRITICAL: Python 3.11+ required (Article II Rule 3)")
    sys.exit(2)


class FlywheelHealth(Enum):
    """Flywheel health status."""
    THRIVING = "thriving"
    HEALTHY = "healthy"
    WARNING = "warning"
    CRITICAL = "critical"
    STALLED = "stalled"


class PatternSeverity(Enum):
    """Failure pattern severity."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class FailurePattern:
    """Detected failure pattern."""
    error_code: str
    frequency: int
    first_seen: str
    last_seen: str
    affected_files: List[str]
    trend: str  # "increasing", "stable", "decreasing"
    severity: PatternSeverity
    recommendation: str
    
    def to_dict(self) -> Dict:
        return {
            **asdict(self),
            "severity": self.severity.value
        }


@dataclass
class FlywheelMetrics:
    """Metrics for a single flywheel."""
    name: str
    health: FlywheelHealth
    primary_metric: float
    secondary_metrics: Dict[str, float]
    trend: str  # "growing", "stable", "declining"
    last_updated: str
    insights: List[str]
    
    def to_dict(self) -> Dict:
        return {
            **asdict(self),
            "health": self.health.value
        }


@dataclass
class AmendmentProposal:
    """Constitutional amendment proposal."""
    proposal_id: str
    title: str
    problem_statement: str
    evidence: List[Dict]
    proposed_change: str
    affected_articles: List[str]
    impact_assessment: str
    rollout_steps: List[str]
    created: str
    status: str  # "draft", "pending_review", "approved", "rejected"
    
    def to_dict(self) -> Dict:
        return asdict(self)
    
    def to_markdown(self) -> str:
        """Generate markdown proposal document."""
        lines = [
            f"# Constitutional Amendment Proposal",
            f"",
            f"**Proposal ID**: {self.proposal_id}",
            f"**Status**: {self.status}",
            f"**Created**: {self.created}",
            f"",
            f"---",
            f"",
            f"## Problem Statement",
            f"",
            f"{self.problem_statement}",
            f"",
            f"---",
            f"",
            f"## Evidence",
            f""
        ]
        
        for i, ev in enumerate(self.evidence, 1):
            lines.append(f"### Evidence {i}")
            lines.append(f"- **Source**: {ev.get('source', 'N/A')}")
            lines.append(f"- **Date**: {ev.get('date', 'N/A')}")
            lines.append(f"- **Details**: {ev.get('details', 'N/A')}")
            lines.append("")
        
        lines.extend([
            f"---",
            f"",
            f"## Proposed Change",
            f"",
            f"{self.proposed_change}",
            f"",
            f"**Affected Articles**: {', '.join(self.affected_articles)}",
            f"",
            f"---",
            f"",
            f"## Impact Assessment",
            f"",
            f"{self.impact_assessment}",
            f"",
            f"---",
            f"",
            f"## Rollout Steps",
            f""
        ])
        
        for i, step in enumerate(self.rollout_steps, 1):
            lines.append(f"{i}. {step}")
        
        lines.extend([
            f"",
            f"---",
            f"",
            f"*Generated by Flywheel Analyst (Agent Omega)*",
            f"*Constitutional Authority: EPOS_CONSTITUTION_v3.1.md Article IX*"
        ])
        
        return "\n".join(lines)


class FlywheelAnalyst:
    """
    Flywheel Analyst - Agent Omega
    
    Analyzes BI logs and proposes governance improvements.
    """
    
    # Thresholds for pattern detection
    PATTERN_THRESHOLDS = {
        "same_error_warning": 3,      # 3+ same error in 24h = warning
        "same_error_critical": 10,    # 10+ same error in 7d = critical
        "compliance_warning": 85,     # < 85% compliance = warning
        "compliance_critical": 75,    # < 75% compliance = critical
        "amendment_trigger": 3        # 3+ sprints with pattern = propose amendment
    }
    
    # Flywheel definitions
    FLYWHEELS = {
        "content": {
            "name": "Content Flywheel",
            "description": "Content output drives engagement drives data drives better content",
            "primary_metric": "pieces_per_week",
            "secondary_metrics": ["engagement_rate", "repurpose_ratio", "distribution_reach"],
            "health_thresholds": {
                "thriving": 20,
                "healthy": 10,
                "warning": 5,
                "critical": 1
            }
        },
        "revenue": {
            "name": "Revenue Flywheel",
            "description": "Node sales drive development drive better nodes drive more sales",
            "primary_metric": "mrr_usd",
            "secondary_metrics": ["node_units_sold", "churn_rate", "expansion_revenue"],
            "health_thresholds": {
                "thriving": 5000,
                "healthy": 1000,
                "warning": 100,
                "critical": 0
            }
        },
        "data_moat": {
            "name": "Data Moat Flywheel",
            "description": "More data improves models improves output improves data capture",
            "primary_metric": "vault_size_mb",
            "secondary_metrics": ["unique_sources", "query_depth", "context_utilization"],
            "health_thresholds": {
                "thriving": 1000,
                "healthy": 100,
                "warning": 10,
                "critical": 0
            }
        },
        "sovereign_scaling": {
            "name": "Sovereign Scaling Flywheel",
            "description": "Independence enables composability enables market reach enables more independence",
            "primary_metric": "nodes_independent_pct",
            "secondary_metrics": ["bundle_combinations", "vendor_dependencies", "portability_score"],
            "health_thresholds": {
                "thriving": 100,
                "healthy": 80,
                "warning": 50,
                "critical": 0
            }
        }
    }
    
    def __init__(self, epos_root: Optional[Path] = None, verbose: bool = False):
        """Initialize the Flywheel Analyst."""
        self.epos_root = epos_root or Path(os.getenv("EPOS_ROOT", "C:/Users/Jamie/workspace/epos_mcp"))
        self.verbose = verbose
        
        # Load environment
        self._load_environment()
    
    def _load_environment(self):
        """Load .env file."""
        try:
            from dotenv import load_dotenv
            env_path = self.epos_root / ".env"
            if env_path.exists():
                load_dotenv(env_path)
        except ImportError:
            pass
    
    def _log(self, message: str):
        """Print message if verbose."""
        if self.verbose:
            print(f"[Analyst] {message}")
    
    def _get_bi_log(self) -> Dict:
        """Load BI decision log."""
        bi_log_path = self.epos_root / "bi_decision_log.json"
        
        if not bi_log_path.exists():
            return {"decisions": []}
        
        try:
            return json.loads(bi_log_path.read_text())
        except json.JSONDecodeError:
            return {"decisions": []}
    
    def _save_bi_log(self, bi_data: Dict):
        """Save BI decision log."""
        bi_log_path = self.epos_root / "bi_decision_log.json"
        bi_log_path.write_text(json.dumps(bi_data, indent=2))
    
    # =========================================================================
    # FAILURE PATTERN DETECTION
    # =========================================================================
    
    def detect_failure_patterns(self, days: int = 7) -> List[FailurePattern]:
        """
        Detect failure patterns from BI logs.
        
        Workflow: failure_pattern_detection
        """
        self._log(f"Analyzing failure patterns for last {days} days...")
        
        bi_data = self._get_bi_log()
        decisions = bi_data.get("decisions", [])
        
        # Filter to recent decisions
        cutoff = datetime.now() - timedelta(days=days)
        recent = []
        
        for d in decisions:
            try:
                ts = datetime.fromisoformat(d.get("timestamp", "2020-01-01"))
                if ts >= cutoff:
                    recent.append(d)
            except:
                continue
        
        # Aggregate error codes
        error_counts = Counter()
        error_files = {}
        error_timestamps = {}
        
        for d in recent:
            # From arbiter triage
            if d.get("agent") == "constitutional_arbiter":
                violations = d.get("violations_summary", {})
                for code, count in violations.items():
                    error_counts[code] += count
                    
                    if code not in error_files:
                        error_files[code] = set()
                    files = d.get("files", {}).get("rejected", [])
                    error_files[code].update(files)
                    
                    if code not in error_timestamps:
                        error_timestamps[code] = {"first": d["timestamp"], "last": d["timestamp"]}
                    else:
                        error_timestamps[code]["last"] = d["timestamp"]
        
        # Build patterns
        patterns = []
        
        for code, count in error_counts.most_common():
            # Determine severity
            if count >= self.PATTERN_THRESHOLDS["same_error_critical"]:
                severity = PatternSeverity.CRITICAL
            elif count >= self.PATTERN_THRESHOLDS["same_error_warning"]:
                severity = PatternSeverity.HIGH
            elif count >= 3:
                severity = PatternSeverity.MEDIUM
            else:
                severity = PatternSeverity.LOW
            
            # Generate recommendation
            recommendation = self._generate_recommendation(code, count)
            
            patterns.append(FailurePattern(
                error_code=code,
                frequency=count,
                first_seen=error_timestamps.get(code, {}).get("first", "unknown"),
                last_seen=error_timestamps.get(code, {}).get("last", "unknown"),
                affected_files=list(error_files.get(code, [])),
                trend="increasing" if count > 5 else "stable",
                severity=severity,
                recommendation=recommendation
            ))
        
        self._log(f"  Detected {len(patterns)} patterns")
        return patterns
    
    def _generate_recommendation(self, error_code: str, count: int) -> str:
        """Generate recommendation for an error pattern."""
        recommendations = {
            "ERR-PATH-001": "Add pre-commit hook to validate path formats before submission",
            "ERR-HEADER-001": "Add IDE snippet/template for constitutional file headers",
            "ERR-CONFIG-001": "Update project template to include load_dotenv() in all entrypoints",
            "ERR-CONTEXT-001": "Implement automatic vault ingestion for files >50KB",
            "ERR-SYNTAX-001": "Add syntax validation to CI pipeline before arbiter review",
            "ERR-TRUTH-001": "Refactor execution bridge to require proof objects in all responses"
        }
        
        base = recommendations.get(error_code, f"Review {error_code} in FAILURE_SCENARIOS.md")
        
        if count >= 10:
            base += ". CRITICAL: Consider constitutional amendment to address root cause."
        
        return base
    
    # =========================================================================
    # FLYWHEEL METRIC TRACKING
    # =========================================================================
    
    def calculate_flywheel_metrics(self) -> Dict[str, FlywheelMetrics]:
        """
        Calculate metrics for all four flywheels.
        
        Workflow: flywheel_metric_tracking
        """
        self._log("Calculating flywheel metrics...")
        
        metrics = {}
        
        # Content Flywheel
        metrics["content"] = self._calculate_content_flywheel()
        
        # Revenue Flywheel
        metrics["revenue"] = self._calculate_revenue_flywheel()
        
        # Data Moat Flywheel
        metrics["data_moat"] = self._calculate_data_moat_flywheel()
        
        # Sovereign Scaling Flywheel
        metrics["sovereign_scaling"] = self._calculate_sovereign_flywheel()
        
        return metrics
    
    def _calculate_content_flywheel(self) -> FlywheelMetrics:
        """Calculate Content Flywheel metrics."""
        # Try to read content lab logs
        content_log_path = self.epos_root / "ops" / "logs" / "content_lab.json"
        
        pieces_per_week = 0
        engagement_rate = 0.0
        repurpose_ratio = 0.0
        
        if content_log_path.exists():
            try:
                data = json.loads(content_log_path.read_text())
                pieces_per_week = data.get("pieces_this_week", 0)
                engagement_rate = data.get("avg_engagement", 0.0)
                repurpose_ratio = data.get("repurpose_ratio", 0.0)
            except:
                pass
        
        # Determine health
        thresholds = self.FLYWHEELS["content"]["health_thresholds"]
        if pieces_per_week >= thresholds["thriving"]:
            health = FlywheelHealth.THRIVING
        elif pieces_per_week >= thresholds["healthy"]:
            health = FlywheelHealth.HEALTHY
        elif pieces_per_week >= thresholds["warning"]:
            health = FlywheelHealth.WARNING
        elif pieces_per_week >= thresholds["critical"]:
            health = FlywheelHealth.CRITICAL
        else:
            health = FlywheelHealth.STALLED
        
        # Generate insights
        insights = []
        if pieces_per_week == 0:
            insights.append("No content produced this week - Content Lab may need activation")
        if repurpose_ratio < 0.3:
            insights.append("Low repurpose ratio - consider cascade automation")
        
        return FlywheelMetrics(
            name="Content Flywheel",
            health=health,
            primary_metric=pieces_per_week,
            secondary_metrics={
                "engagement_rate": engagement_rate,
                "repurpose_ratio": repurpose_ratio
            },
            trend="stable",
            last_updated=datetime.now().isoformat(),
            insights=insights
        )
    
    def _calculate_revenue_flywheel(self) -> FlywheelMetrics:
        """Calculate Revenue Flywheel metrics."""
        # Try to read node business data
        business_path = self.epos_root / "NODE_BUSINESS_CARDS.md"
        
        mrr = 0.0
        units_sold = 0
        
        if business_path.exists():
            try:
                content = business_path.read_text()
                # Extract revenue from NODE_BUSINESS_CARDS.md
                mrr_match = re.search(r'\$(\d+(?:,\d+)?)/mo', content)
                if mrr_match:
                    mrr = float(mrr_match.group(1).replace(',', ''))
            except:
                pass
        
        # Determine health
        thresholds = self.FLYWHEELS["revenue"]["health_thresholds"]
        if mrr >= thresholds["thriving"]:
            health = FlywheelHealth.THRIVING
        elif mrr >= thresholds["healthy"]:
            health = FlywheelHealth.HEALTHY
        elif mrr >= thresholds["warning"]:
            health = FlywheelHealth.WARNING
        elif mrr >= thresholds["critical"]:
            health = FlywheelHealth.CRITICAL
        else:
            health = FlywheelHealth.STALLED
        
        insights = []
        if mrr == 0:
            insights.append("No revenue yet - focus on first node sale or pilot")
        
        return FlywheelMetrics(
            name="Revenue Flywheel",
            health=health,
            primary_metric=mrr,
            secondary_metrics={
                "units_sold": units_sold,
                "churn_rate": 0.0
            },
            trend="stable",
            last_updated=datetime.now().isoformat(),
            insights=insights
        )
    
    def _calculate_data_moat_flywheel(self) -> FlywheelMetrics:
        """Calculate Data Moat Flywheel metrics."""
        # Read vault registry
        vault_registry_path = self.epos_root / "context_vault" / "registry.json"
        
        vault_size_mb = 0.0
        vault_count = 0
        
        if vault_registry_path.exists():
            try:
                registry = json.loads(vault_registry_path.read_text())
                vaults = registry.get("vaults", {})
                vault_count = len(vaults)
                total_bytes = sum(v.get("size_bytes", 0) for v in vaults.values())
                vault_size_mb = total_bytes / (1024 * 1024)
            except:
                pass
        
        # Determine health
        thresholds = self.FLYWHEELS["data_moat"]["health_thresholds"]
        if vault_size_mb >= thresholds["thriving"]:
            health = FlywheelHealth.THRIVING
        elif vault_size_mb >= thresholds["healthy"]:
            health = FlywheelHealth.HEALTHY
        elif vault_size_mb >= thresholds["warning"]:
            health = FlywheelHealth.WARNING
        elif vault_size_mb >= thresholds["critical"]:
            health = FlywheelHealth.CRITICAL
        else:
            health = FlywheelHealth.STALLED
        
        insights = []
        if vault_size_mb < 10:
            insights.append("Data moat is thin - prioritize data ingestion and context capture")
        
        return FlywheelMetrics(
            name="Data Moat Flywheel",
            health=health,
            primary_metric=vault_size_mb,
            secondary_metrics={
                "vault_count": vault_count,
                "query_depth": 0
            },
            trend="growing" if vault_size_mb > 0 else "stalled",
            last_updated=datetime.now().isoformat(),
            insights=insights
        )
    
    def _calculate_sovereign_flywheel(self) -> FlywheelMetrics:
        """Calculate Sovereign Scaling Flywheel metrics."""
        # Check node sovereignty
        nodes_dir = self.epos_root / "nodes"
        
        total_nodes = 0
        independent_nodes = 0
        
        if nodes_dir.exists():
            for node_dir in nodes_dir.iterdir():
                if node_dir.is_dir():
                    total_nodes += 1
                    
                    # Check for node_manifest.json
                    manifest = node_dir / "node_manifest.json"
                    if manifest.exists():
                        try:
                            data = json.loads(manifest.read_text())
                            if data.get("sovereignty_tests_passed", False):
                                independent_nodes += 1
                        except:
                            pass
        
        pct = (independent_nodes / total_nodes * 100) if total_nodes > 0 else 0
        
        # Determine health
        thresholds = self.FLYWHEELS["sovereign_scaling"]["health_thresholds"]
        if pct >= thresholds["thriving"]:
            health = FlywheelHealth.THRIVING
        elif pct >= thresholds["healthy"]:
            health = FlywheelHealth.HEALTHY
        elif pct >= thresholds["warning"]:
            health = FlywheelHealth.WARNING
        elif pct >= thresholds["critical"]:
            health = FlywheelHealth.CRITICAL
        else:
            health = FlywheelHealth.STALLED
        
        insights = []
        if total_nodes == 0:
            insights.append("No nodes defined - begin with Research or Analysis node")
        elif independent_nodes < total_nodes:
            insights.append(f"{total_nodes - independent_nodes} nodes need sovereignty validation")
        
        return FlywheelMetrics(
            name="Sovereign Scaling Flywheel",
            health=health,
            primary_metric=pct,
            secondary_metrics={
                "total_nodes": total_nodes,
                "independent_nodes": independent_nodes
            },
            trend="stable",
            last_updated=datetime.now().isoformat(),
            insights=insights
        )
    
    # =========================================================================
    # AMENDMENT PROPOSER
    # =========================================================================
    
    def should_propose_amendment(self, patterns: List[FailurePattern]) -> List[FailurePattern]:
        """Check if any patterns warrant a constitutional amendment."""
        amendment_candidates = []
        
        for pattern in patterns:
            if pattern.severity in [PatternSeverity.CRITICAL, PatternSeverity.HIGH]:
                if pattern.frequency >= self.PATTERN_THRESHOLDS["amendment_trigger"]:
                    amendment_candidates.append(pattern)
        
        return amendment_candidates
    
    def propose_amendment(self, pattern: FailurePattern) -> AmendmentProposal:
        """
        Generate a constitutional amendment proposal.
        
        Workflow: amendment_proposer
        """
        proposal_id = f"AMEND-{datetime.now().strftime('%Y%m%d')}-{pattern.error_code}"
        
        # Build evidence
        evidence = [
            {
                "source": "BI Decision Log",
                "date": pattern.last_seen,
                "details": f"Error {pattern.error_code} occurred {pattern.frequency} times"
            },
            {
                "source": "Affected Files",
                "date": pattern.last_seen,
                "details": f"Files affected: {', '.join(pattern.affected_files[:5])}"
            }
        ]
        
        # Map error codes to proposed changes
        proposed_changes = {
            "ERR-PATH-001": "Add Article II Rule 1.1: All path operations MUST use pathlib.Path with explicit str() conversion for external APIs.",
            "ERR-HEADER-001": "Add Article II Rule 5.1: IDE integration MUST provide file header templates. Governance gate MUST provide one-click fix.",
            "ERR-CONFIG-001": "Add Article II Rule 6.1: Project scaffolding MUST include load_dotenv() in all generated entrypoints.",
            "ERR-CONTEXT-001": "Add Article VII Rule 1.4: Files exceeding 50KB MUST be automatically triaged to Context Vault ingestion.",
            "ERR-TRUTH-001": "Add Article II Rule 4.1: All status responses MUST include proof object with verifiable execution artifacts."
        }
        
        proposed_change = proposed_changes.get(
            pattern.error_code,
            f"Add new rule addressing {pattern.error_code}: {pattern.recommendation}"
        )
        
        # Determine affected articles
        affected_articles = []
        if "PATH" in pattern.error_code:
            affected_articles.append("Article II (Hard Boundaries)")
        if "HEADER" in pattern.error_code:
            affected_articles.append("Article II (Hard Boundaries)")
        if "CONTEXT" in pattern.error_code:
            affected_articles.append("Article VII (Context Governance)")
        if not affected_articles:
            affected_articles.append("Article III (Quality Gates)")
        
        return AmendmentProposal(
            proposal_id=proposal_id,
            title=f"Address Recurring {pattern.error_code} Violations",
            problem_statement=f"The error code {pattern.error_code} has occurred {pattern.frequency} times in the past week, affecting {len(pattern.affected_files)} files. This indicates a systemic gap in the current constitutional framework that requires formal amendment.",
            evidence=evidence,
            proposed_change=proposed_change,
            affected_articles=affected_articles,
            impact_assessment=f"This amendment will prevent approximately {pattern.frequency} violations per week, reducing debugging time by an estimated {pattern.frequency * 15} minutes weekly.",
            rollout_steps=[
                f"Update EPOS_CONSTITUTION_v3.1.md with proposed change",
                f"Update governance_gate.py to enforce new rule",
                f"Update epos_doctor.py to check for compliance",
                f"Notify all agents of constitutional update",
                f"Run sprint audit to verify enforcement"
            ],
            created=datetime.now().isoformat(),
            status="draft"
        )
    
    # =========================================================================
    # REPORT GENERATION
    # =========================================================================
    
    def generate_weekly_report(self) -> Dict:
        """
        Generate comprehensive weekly flywheel report.
        """
        self._log("Generating weekly report...")
        
        # Get patterns
        patterns = self.detect_failure_patterns(days=7)
        
        # Get flywheel metrics
        flywheel_metrics = self.calculate_flywheel_metrics()
        
        # Check for amendment candidates
        amendment_candidates = self.should_propose_amendment(patterns)
        
        # Generate proposals if needed
        proposals = []
        for candidate in amendment_candidates:
            proposal = self.propose_amendment(candidate)
            proposals.append(proposal)
        
        # Calculate overall health
        healths = [m.health for m in flywheel_metrics.values()]
        critical_count = sum(1 for h in healths if h in [FlywheelHealth.CRITICAL, FlywheelHealth.STALLED])
        warning_count = sum(1 for h in healths if h == FlywheelHealth.WARNING)
        
        if critical_count > 0:
            overall_health = "CRITICAL"
        elif warning_count > 1:
            overall_health = "WARNING"
        else:
            overall_health = "HEALTHY"
        
        report = {
            "timestamp": datetime.now().isoformat(),
            "period": "weekly",
            "overall_health": overall_health,
            "flywheels": {k: v.to_dict() for k, v in flywheel_metrics.items()},
            "failure_patterns": [p.to_dict() for p in patterns],
            "amendment_proposals": [p.to_dict() for p in proposals],
            "summary": {
                "total_patterns": len(patterns),
                "critical_patterns": sum(1 for p in patterns if p.severity == PatternSeverity.CRITICAL),
                "amendments_proposed": len(proposals),
                "flywheels_thriving": sum(1 for m in flywheel_metrics.values() if m.health == FlywheelHealth.THRIVING),
                "flywheels_at_risk": critical_count + warning_count
            }
        }
        
        # Save report
        reports_dir = self.epos_root / "ops" / "flywheel_reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        
        report_path = reports_dir / f"{datetime.now().strftime('%Y%m%d')}_metrics.json"
        report_path.write_text(json.dumps(report, indent=2))
        
        # Save markdown dashboard
        dashboard_path = reports_dir / f"{datetime.now().strftime('%Y%m%d')}_dashboard.md"
        dashboard_path.write_text(self._generate_dashboard_markdown(report))
        
        # Save amendment proposals
        if proposals:
            amendments_dir = self.epos_root / "inbox" / "amendments"
            amendments_dir.mkdir(parents=True, exist_ok=True)
            
            for proposal in proposals:
                proposal_path = amendments_dir / f"{proposal.proposal_id}.md"
                proposal_path.write_text(proposal.to_markdown())
        
        # Log to BI
        self._log_to_bi(report)
        
        return report
    
    def _generate_dashboard_markdown(self, report: Dict) -> str:
        """Generate markdown dashboard from report."""
        lines = [
            f"# EPOS Flywheel Dashboard",
            f"",
            f"**Generated**: {report['timestamp']}",
            f"**Overall Health**: {report['overall_health']}",
            f"",
            f"---",
            f"",
            f"## Flywheel Status",
            f""
        ]
        
        for name, metrics in report["flywheels"].items():
            emoji = {
                "thriving": "🚀",
                "healthy": "✅",
                "warning": "⚠️",
                "critical": "🔴",
                "stalled": "⛔"
            }.get(metrics["health"], "❓")
            
            lines.append(f"### {emoji} {metrics['name']}")
            lines.append(f"")
            lines.append(f"- **Health**: {metrics['health'].upper()}")
            lines.append(f"- **Primary Metric**: {metrics['primary_metric']}")
            lines.append(f"- **Trend**: {metrics['trend']}")
            
            if metrics.get("insights"):
                lines.append(f"- **Insights**:")
                for insight in metrics["insights"]:
                    lines.append(f"  - {insight}")
            lines.append("")
        
        lines.extend([
            f"---",
            f"",
            f"## Failure Patterns",
            f""
        ])
        
        if report["failure_patterns"]:
            lines.append("| Error Code | Frequency | Severity | Recommendation |")
            lines.append("|------------|-----------|----------|----------------|")
            for p in report["failure_patterns"][:10]:
                lines.append(f"| {p['error_code']} | {p['frequency']} | {p['severity']} | {p['recommendation'][:50]}... |")
        else:
            lines.append("*No failure patterns detected* ✅")
        
        lines.extend([
            f"",
            f"---",
            f"",
            f"## Amendment Proposals",
            f""
        ])
        
        if report["amendment_proposals"]:
            for prop in report["amendment_proposals"]:
                lines.append(f"- **{prop['proposal_id']}**: {prop['title']}")
        else:
            lines.append("*No amendments needed* ✅")
        
        lines.extend([
            f"",
            f"---",
            f"",
            f"*Generated by Flywheel Analyst (Agent Omega)*"
        ])
        
        return "\n".join(lines)
    
    def _log_to_bi(self, report: Dict):
        """Log report to BI decision log."""
        bi_data = self._get_bi_log()
        
        bi_data["decisions"].append({
            "agent": "flywheel_analyst",
            "action": "weekly_report",
            "timestamp": report["timestamp"],
            "overall_health": report["overall_health"],
            "summary": report["summary"]
        })
        
        self._save_bi_log(bi_data)


def main():
    """CLI entrypoint for Flywheel Analyst."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Flywheel Analyst (Agent Omega)")
    parser.add_argument("--patterns", action="store_true", help="Detect failure patterns")
    parser.add_argument("--flywheels", action="store_true", help="Calculate flywheel metrics")
    parser.add_argument("--report", action="store_true", help="Generate weekly report")
    parser.add_argument("--days", type=int, default=7, help="Analysis period in days")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument("--json", "-j", action="store_true", help="JSON output")
    
    args = parser.parse_args()
    
    analyst = FlywheelAnalyst(verbose=args.verbose)
    
    if args.patterns:
        patterns = analyst.detect_failure_patterns(days=args.days)
        
        if args.json:
            print(json.dumps([p.to_dict() for p in patterns], indent=2))
        else:
            print(f"\n🔍 Failure Patterns (last {args.days} days)")
            for p in patterns:
                emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}
                print(f"  {emoji.get(p.severity.value, '❓')} {p.error_code}: {p.frequency}x - {p.recommendation[:60]}...")
        
        sys.exit(0)
    
    elif args.flywheels:
        metrics = analyst.calculate_flywheel_metrics()
        
        if args.json:
            print(json.dumps({k: v.to_dict() for k, v in metrics.items()}, indent=2))
        else:
            print("\n🎡 Flywheel Metrics")
            for name, m in metrics.items():
                emoji = {
                    "thriving": "🚀",
                    "healthy": "✅",
                    "warning": "⚠️",
                    "critical": "🔴",
                    "stalled": "⛔"
                }.get(m.health.value, "❓")
                print(f"  {emoji} {m.name}: {m.primary_metric} ({m.health.value})")
        
        sys.exit(0)
    
    elif args.report:
        report = analyst.generate_weekly_report()
        
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"\n📊 Weekly Report Generated")
            print(f"   Overall Health: {report['overall_health']}")
            print(f"   Patterns Found: {report['summary']['total_patterns']}")
            print(f"   Amendments Proposed: {report['summary']['amendments_proposed']}")
            print(f"   Flywheels Thriving: {report['summary']['flywheels_thriving']}/4")
        
        # Exit based on health
        if report["overall_health"] == "CRITICAL":
            sys.exit(2)
        elif report["overall_health"] == "WARNING":
            sys.exit(1)
        else:
            sys.exit(0)
    
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
